version: '3.8'

services:
    webapp:
        image: ghcr.io/xmlking/svelte-starter-kit:latest
        init: true
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
