query {
	counts: tz_policies_aggregate {
		aggregate {
			count
		}
	}
	tz_policies(order_by: { update_time: desc_nulls_last }, limit: 10, where: { delete_time: { _is_null: true } }) {
		id
		create_time
		display_name
		subject_id
		subject_secondary_id
		subject_domain
		subject_display_name
		subject_type
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}

query ($subject_id: String, $subject_type: String = "subject_type_user", $limit: Int = 50) {
	tz_policies(order_by: { update_time: desc_nulls_last }, limit: $limit, where: { delete_time: { _is_null: true }, subject_id: { _eq: $subject_id }, subject_type: { _eq: $subject_type }, display_name: { _like: "%user%" } }) {
		id
		create_time
		display_name
		subject_type
		subject_display_name
		subject_id
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}

query ($id: uuid!) {
	tz_policies_by_pk(id: $id) {
		id
		create_time
		display_name
		subject_type
		subject_display_name
		subject_id
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}


query ($subject_id: String, $subject_type: String = "subject_type_user", $limit: Int = 50) {
	tz_policies(order_by: { update_time: desc_nulls_last }, limit: $limit, where: { delete_time: { _is_null: true }, subject_id: { _eq: $subject_id }, subject_type: { _eq: $subject_type } }) {
		id
		create_time
		display_name
		subject_type
		subject_display_name
		subject_id
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}
{
  "subject_id": "6e9bf365-8c09-4dd9-b9b2-83f6ab315618",
  "subject_type": "subject_type_user"
}


mutation $id: uuid) {
  delete_tz_policies_by_pk(id: $id)
}
