query {
	counts: tz_policies_aggregate {
		aggregate {
			count
		}
	}
	tz_policies(order_by: { update_time: desc_nulls_last }, limit: 10, where: { delete_time: { _is_null: true } }) {
		id
		create_time
		display_name
		subject_id
		subject_secondary_id
		subject_domain
		subject_display_name
		subject_type
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}

query ($subject_id: String, $subject_type: String = "subject_type_user", $limit: Int = 50) {
	tz_policies(order_by: { update_time: desc_nulls_last }, limit: $limit, where: { delete_time: { _is_null: true }, subject_id: { _eq: $subject_id }, subject_type: { _eq: $subject_type }, display_name: { _like: "%user%" } }) {
		id
		create_time
		display_name
		subject_type
		subject_display_name
		subject_id
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}

query ($id: uuid!) {
	tz_policies_by_pk(id: $id) {
		id
		create_time
		display_name
		subject_type
		subject_display_name
		subject_id
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}


query ($subject_id: String, $subject_type: String = "subject_type_user", $limit: Int = 50) {
	tz_policies(order_by: { update_time: desc_nulls_last }, limit: $limit, where: { delete_time: { _is_null: true }, subject_id: { _eq: $subject_id }, subject_type: { _eq: $subject_type } }) {
		id
		create_time
		display_name
		subject_type
		subject_display_name
		subject_id
		valid_from
		valid_to
		weight
		source_address
		source_port
		destination_address
		destination_port
		protocol
		action
		template
	}
}
{
  "subject_id": "6e9bf365-8c09-4dd9-b9b2-83f6ab315618",
  "subject_type": "subject_type_user"
}


mutation $id: uuid) {
  delete_tz_policies_by_pk(id: $id)
}


mutation (
  $id: uuid!
  $display_name: String
  $description: String
  $tags: _text
  $annotations: hstore
  $disabled: Boolean
  $template: Boolean
  $subject_id: String
  $subject_secondary_id: String
  $subject_display_name: String
  $subject_type: String
  $subject_domain: String
  $source_address: String
  $source_port: String
  $destination_address: String
  $destination_port: String
  $direction: String = "direction_egress"
  $protocol: String = "Any"
  $action: String = "action_block"
  $weight: Int = 500
  $app_id: String
  $create_time: timestamptz
  $update_time: timestamptz
  $valid_from: timestamptz
) {
  insert_tz_policies_one(
    object: {
      id: $id
      display_name: $display_name
      description: $description
      tags: $tags
      annotations: $annotations
      disabled: $disabled
      template: $template
      subject_id: $subject_id
      subject_secondary_id: $subject_secondary_id
      subject_display_name: $subject_display_name
      subject_type: $subject_type
      subject_domain: $subject_domain
      source_address: $source_address
      source_port: $source_port
      destination_address: $destination_address
      destination_port: $destination_port
      direction: $direction
      protocol: $protocol
      action: $action
      weight: $weight
      app_id: $app_id
      create_time: $create_time
      update_time: $update_time
      valid_from: $valid_from
    }
  ) {
    id
    create_time
    update_time
  }
}


{
  "id" : "{{$guid}}",
  "display_name" :"user 1",
  "description" :"user 1 policy",
  "tags": "{tz,us}",
  "annotations": "\"sumo\"=>\"demo\"",
  "disabled": false,
  "template": false,
  "subject_id": "6e9bf365-8c09-4dd9-b9b2-83f6ab315618",
  "subject_secondary_id": "sumo@chintagunta.com",
  "subject_display_name": "sumanth chinthagunta",
  "subject_type": "subject_type_user",
  "subject_domain": "chintagunta.com",
  "source_address": "0.0.0.0",
  "source_port": "5000",
  "destination_address": "1.1.1.1",
  "destination_port": "443",
  "direction": "direction_egress",
  "protocol": "Any",
  "action": "action_block",
  "weight": 1000,
  "app_id": "myapp.exe",
  "create_time": "{{$datetime rfc1123|iso8601 [offset option]}}",
  "update_time": "{{$datetime rfc1123|iso8601 [offset option]}}",
  "valid_from": "{{$datetime rfc1123|iso8601 [offset option]}}",
}
