query SearchPolicies($where: tz_policies_bool_exp, $limit: Int = 50, $offset: Int = 0, $orderBy: [tz_policies_order_by!] = [{ updated_at: desc_nulls_last }]) {
	counts: tz_policies_aggregate(where: $where) {
		aggregate {
			count
		}
	}
	tz_policies(order_by: $orderBy, limit: $limit, offset: $offset, where: $where) {
		# ...Policy_list_fields @mask_disable
		id
		created_at
		destination_address
		destination_port
		disabled
		display_name
		source_address
		source_port
		subject_display_name
		template
		updated_at
	}
}
