- name: postgresdb
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      # pool_settings:
      #   idle_timeout: 180
      #   max_connections: 50
      #   retries: 1
      use_prepared_statements: false
  tables: "!include postgresdb/tables/tables.yaml"
