table:
  name: customer
  schema: public
array_relationships:
  - name: orders
    using:
      foreign_key_constraint_on:
        column: customer_id
        table:
          name: order
          schema: public
